### ISSUE TITLE
Add ipopt package

### ISSUE THREAD

**Issue by astrojuanlu** [CAChemE/pyomo-recipes#1]
I need @franktoffel to tell me what binaries to put there exactly.

**Comment by franktoffel** [comment]
https://github.com/CAChemE/pyomo-instalacion/tree/master/solvers/Windows/Ipopt-3.11.1-win64-intel13.1/bin

**Comment by franktoffel** [comment]
It would be nice to have a single package in anaconda.org that includes the binaries either for windows or linux/mac. 

Windows, 64 bit <-- tested on my machine :+1: 
http://www.coin-or.org/download/binary/Ipopt/Ipopt-3.11.1-win64-intel13.1.zip

Windows, 32 bit (only if necessary)
http://www.coin-or.org/download/binary/Ipopt/Ipopt-3.11.1-win32-cl16ifort13.1.zip

Linux/Mac
Apparently, these are the only binaries I can find [here](http://www.coin-or.org/download/binary/Ipopt/) that are not compiled for MATLAB (i.e. mex files)
http://www.coin-or.org/download/binary/Ipopt/Ipopt-3.11.1-mac-osx-x86_64-gcc4.5.3.tgz

**Comment by astrojuanlu** [comment]
Package for Windows x64 was already added. I will leave the issue open though.

**Comment by astrojuanlu** [comment]
Actually I'm not entirely sure that the latest binaries will work for Linux. I find it annoying that they are not consistent when providing them for all the platforms, but I foresee that actually compiling them can be a nightmare so I'm not (yet) trying.

This is the most recent Linux binary:

http://www.coin-or.org/download/binary/Ipopt/Ipopt-3.7.1-linux-x86_64-gcc4.3.2.tgz

As there is a version mismatch I will have to provide a different package. No worries.

**Comment by franktoffel** [comment]
You are right, looks like different binary versions for different OS (annoying)
