### ISSUE TITLE
 Windows 10 & Pyomo 4.2.10784 & Gurobi 6.5.1: Solver returns 'None' values 

### ISSUE THREAD

**Issue by ckaldemeyer** [CAChemE/pyomo-recipes#15]
Hi everybody,

I had a weird error with your recipe on two Windows 10 X64 EDU installations:

Gurobi returns [None, None, ...] for the decision variables wheras other solvers e.g. "glpk" work fine. Gurobi itself is licensed and all Gurobi API examples are working. To the solver itself should be fine.

I reported and solved the problem here: https://groups.google.com/forum/#!topic/pyomo-forum/KrTMryO69f8

Short form: Installing the newest version (4.3.11388) via pip solved the problem for me.

Are you planning to provide the newest version in your recipe?

This would fix the error and using you recipe is more convenient than going the manual way.

Cheers
Cord

**Comment by astrojuanlu** [comment]
Can you try the `conda-forge` channel? There is where new developments are going:

``` bash
conda install -c conda-forge pyomo
```

https://anaconda.org/conda-forge/pyomo

**Comment by ckaldemeyer** [comment]
Works!

Are you also planning to provide a conda forge package for pyomo.extras?

**Comment by astrojuanlu** [comment]
Great! Closing then :smile:

**Comment by astrojuanlu** [comment]
It shouldn't be difficult to migrate pyomo.extras to conda-forge too, perhaps @whart222 has some plans on this.
