### ISSUE TITLE
Installing Pyomo Windows10

### ISSUE THREAD

**Issue by MichaelM73** [CAChemE/pyomo-recipes#16]
I am trying to install pyomo in Windows 10. My steps are:

Install Anaconda 2.7
Install Pyomo: conda install -c conda-forge pyomo
Install ipopt: conda install ipopt_bin --channel cachemeorg
But I am having the next error:

_Exception in thread Thread-6:
Traceback (most recent call last):
  File "C:\Users\MC\Anaconda2\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Users\MC\Anaconda2\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\MC\Anaconda2\lib\site-packages\pyutilib\subprocess\processmngr.py", line 332, in _merged_reader
    char = s.data.decode(encoding)
LookupError: unknown encoding: cp0

ERROR: "[base]\site-packages\pyomo\opt\base\solvers.py", 599, solve
        Solver (asl) returned non-zero return code (-1073741510)
ERROR: "[base]\site-packages\pyomo\opt\base\solvers.py", 602, solve
        See the solver log above for diagnostic information.
Traceback (most recent call last):

The program is working well from the terminal, but from spyder I get the error above. any idea?

**Comment by astrojuanlu** [comment]
Hi @MeryCherry, thanks for your bug report. It's very weird that the program works from the terminal but not from Spyder.

Apparently there is some issue with the encodings on Windows. Would you please try downloading Anaconda with Python 3.6 and try again? If this problem is specific of Python 2 I fear I won't be able to help because I don't use it anymore.

**Comment by MichaelM73** [comment]
Hola Juanlu, ¿cómo me recomiendas instalar pyomo con Python 3.6? He instalado Anaconda con Python 3.6, ¿Cómo hago ahora para instalar pyomo? ¿e ipopt?

He desinstalado todo lo que tenía hasta ahora. A ver si consigo no tener problemas ahora... Muchas gracias :)

**Comment by astrojuanlu** [comment]
@MeryCherry ¡Hola! Me acabo de dar cuenta de que los paquetes no están aún para Python 3.6, me he pasado de listo :) Para Python 3.5 lo tienes todo, puedes crear un entorno virtual y por lo demás las instrucciones son las mismas, conda install pyomo e ipopt. ¡Si tienes más dudas avísanos por aquí!

**Comment by MichaelM73** [comment]
Muchas gracias Juanlu, pero nada. Sigo sin conseguirlo. He creado un entorno virtual para Python3.5, siguiendo las instrucciones de: https://github.com/CAChemE/pyomo-instalacion y nada, me da error. Ahora he instalado Anaconda con 3.6 pero le he cambiado la versión de Python ( conda install python=3.5.1) y me vuelve a pasar lo mismo, en la terminal funciona pero con Spyder me da otro error de codificación: 
```
enconding = sys.__stdout__.enconding
AttributeError: 'NoneType' object has no attribute 'enconding'
```

¿Alguna idea? Está empezando a desesperarme ya... :(

**Comment by MichaelM73** [comment]
Además, me está ocurriendo algo raro... al ejecutar desde spyder se abre una ventana de comandos con el solver pero se queda negra (C:\Users\MC\Anaconda3\Library\bin\ipopt.exe) y hasta que no la cierro, el terminal de IPython no acaba el proceso....

**Comment by astrojuanlu** [comment]
Es posible que sea un problema con Spyder, ¿podrías copiar la traza completa del error de encoding que te da?

**Comment by MichaelM73** [comment]
Pues... parece que tu magia con Python llega a distancia. Sin hacer nada ha funcionado, y ya compila también en Spyder. No sé qué ha pasado, ni cuánto durará... pero de momento no voy a tocar nada más por si las moscas. Muchas gracias por tu ayuda.
Un saludo, María :)

**Comment by astrojuanlu** [comment]
¡No hay de qué! Mucha suerte y un saludo :)
