### ISSUE TITLE
Error using NEOS

### ISSUE THREAD

**Issue by franktoffel** [CAChemE/pyomo-recipes#5]
After installing pyomo.extras, pyomo is able to connect succesfully with NEOS Server. However, a PermissionError stops the process (only occurs in windows machines).

See https://groups.google.com/forum/#!topic/pyomo-forum/HDSHYa3RDcI

**Comment by astrojuanlu** [comment]
This is the original ticket:

https://software.sandia.gov/trac/pyutilib/ticket/117

It was closed but never solved. Fortunately they suggested a couple of
workarounds in the mailing list. Which one do you think is more convenient?

**Comment by astrojuanlu** [comment]
Actually we could reopen the issue here:

https://github.com/PyUtilib/pyutilib/issues

**Comment by franktoffel** [comment]
Workarounds do not fix the problem, I opened a new ticket here:
https://github.com/PyUtilib/pyutilib/issues/19
